/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdlib.h>
void usart2_clk()
{
	//enable gpio a clock
	uint32_t *gpioa = (uint32_t*)0x40023830;
	*gpioa |= (1 << 0);
	uint32_t *clk = (uint32_t*)0x40023840;
	*clk |= (1 << 17);
}

void usart2_init()
{
	//configure pins
	uint32_t *gpioa_mode = (uint32_t*)0x40020000;
	*gpioa_mode |= (2 << 4) | (2 << 6);
	uint32_t *gpio_alt = (uint32_t*)0x40020020;
	*gpio_alt |= (7 << 8) | (7 << 12);

	uint32_t *cr1 = (uint32_t*)0x4000440c;
	uint32_t *brr = (uint32_t*)0x40004408;

	*cr1 &= 0x00;
	*cr1 |= (1 << 13);
	*brr |= (3 << 0) | (104 << 4);
	*cr1 |= (1 << 2) | (1 << 3);

}

void usart2_send(char c)
{
	uint32_t *dr = (uint32_t*)0x40004404;
	uint32_t *sr = (uint32_t*)0x40004400;

	*dr = c;
	while(!(*sr & (1<<6)));
}

void delay()
{
	for(size_t i = 0; i < 1000000; i++){};
}

int main(void)
{
	usart2_clk();

	usart2_init();

    /* Loop forever */
	while(1)
	{
		usart2_send('x');
		delay();
	}
}
